### ISSUE TITLE
pip 24.1.1 cannot parse pyrr requirements from v.0.1.5 release

### ISSUE THREAD

**Issue by arpie-steele** [becheran/pysg#12]
**Description**
`pip install -U ...` fails when pip has been upgraded to 24.1.1 and pysg was listed.
This was a warning for earlier versions of pip, but now it is an error.

**To Reproduce**
1. With python3.9 or later, create and use a virtual environment.
2. Install pysg (May fail if you already have newer pip)
3. Upgrade pip with `pip install --upgrade pip` (This raises a warning)
4. Attempt to upgrade `pip install -U pysg`
5. See error

**Warning Text from Step 3**

DEPRECATION: pysg 0.1.5 has a non-standard dependency specifier pyrr>=0.10.0<1. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pysg or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

**Partial Error Text from Step 5**
```
Traceback (most recent call last):
  File "${HOME}/${VENV}/lib/python3.9/site-packages/pip/_vendor/packaging/requirements.py", line 36, in __init__
    parsed = _parse_requirement(requirement_string)
  File "${HOME}/${VENV}/lib/python3.9/site-packages/pip/_vendor/packaging/_parser.py", line 62, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "${HOME}/${VENV}/lib/python3.9/site-packages/pip/_vendor/packaging/_parser.py", line 80, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "${HOME}/${VENV}/lib/python3.9/site-packages/pip/_vendor/packaging/_parser.py", line 118, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "${HOME}/${VENV}/lib/python3.9/site-packages/pip/_vendor/packaging/_parser.py", line 215, in _parse_specifier
    tokenizer.consume("WS")
  File "${DIST}/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "${HOME}/${VENV}/lib/python3.9/site-packages/pip/_vendor/packaging/_tokenizer.py", line 189, in enclosing_tokens
    self.raise_syntax_error(
  File "${HOME}/${VENV}/lib/python3.9/site-packages/pip/_vendor/packaging/_tokenizer.py", line 167, in raise_syntax_error
    raise ParserSyntaxError(
pip._vendor.packaging._tokenizer.ParserSyntaxError: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    pyrr (>=0.10.0<1)
         ~~~~~~~~~^
```

**Expected behavior**
No error.

**Additional context**
I believe the problem may be a missing comma on this line:
https://github.com/becheran/pysg/blob/45517711c63785bd33846b8c474d87023451bee7/setup.py#L27

**Comment by arpie-steele** [comment]
This issue is probably common to 0.1.2, 0.1.3, 0.1.4, and 0.1.5 since the change that capped the requirements appears to be 6bf7c0a7
